### ISSUE TITLE
[Feature Request] Add Option For Time Interval To Check For Intelligence Updates Automatically

### ISSUE THREAD

**Issue by OnlinePlayer865** [AndyFul/ConfigureDefender#8]
Hello! I am loving your tool so far. Just installed it yesterday.

One thing I would like to request is the ability to set in the program to then set for Windows Defender for a time interval to check for intelligence updates. This is possible using Group Policy under one of the sections for Defender. I forget which one and I am not currently signed into my Admin user to check under which folder of Defender this resides in under the Policy editor. 

It could be implemented in a couple of ways.
Either a defined # of hours depending on which Setting you choose (Default, High, Max), with the time interval varying depending on the level, or a drop down menu, or text box, to input the time interval to check for intelligence updates. 

I usually have mine set for every hour. I know BitDefender has it's updater checking once an hour. Emsisoft does too I think. Those are the two I have used previously before switching to Windows Defender.

**Comment by AndyFul** [comment]
Thanks for testing. Due to the Cloud delivered protection it is not important if the signatures are updated once a day or every 2 hours. In the end, WD can always use cloud backend to detect threats. The signature detection is far behind the detection of the cloud backend.
The signatures can be important if one uses the computer offline, which is not a case in the home environment. So, I do not plan to add this setting.

Regards.

**Comment by OnlinePlayer865** [comment]
Thank you. I did not know that was the case with Cloud Delivered Protection. Thanks for the info. I can see now that updating the signatures that often, or often at all, is not needed. Going to go ahead and close this issue.
